openapi: 3.0.3
info:
  title: Drink Catalog
  description: Api in which returns drink recipies and the availble rating that is privatly given for the Drink services.
  version: 1.0.0

servers:
  - url: http://localhost:5001/drink
    description: API service for Drink catalog

paths:
  /health:
    get:
      summary: Get the health status of the api
      tags: [Drink]
      responses: 
        '200': 
          description: The api is running and can be called

components:
  schemas:
    GenericObject:
      type: object
      additionalProperties: true