name: CD Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # This could have been set to GITHUB_TOKEN, but I created a GHCR_PAT token instead for more granular control
      # As this is a personal repository, I used my personal account to create the token where GITHUB_TOKEN would be for an origniastion.
      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Will set up Docker Buildx following the docker-compose.yml, but will not run the containers
      - name: Build all services
        run: docker compose -f docker-compose.yml build

      # Run tests in the test containers defined in docker-compose.yml
      - name: Start dependent services
        run: docker compose -f docker-compose.yml up -d mongo

      # Create testing admin and secret keys. TODO verify that this isn't a security error in the future
      - name: Create .env
        run: |
          echo "NODE_ENV=test" > Drink-Catalog/.env
          echo "PORT=5001" >> Drink-Catalog/.env
          echo "MONGO_URI=mongodb://mongo:27017/drink" >> Drink-Catalog/.env
          echo "JWT_SECRET=testsecret" >> Drink-Catalog/.env
          echo "APP_ADMIN_USERNAME=admin" >> Drink-Catalog/.env
          echo "APP_ADMIN_PASSWORD=password123" >> Drink-Catalog/.env

      - name: Run tests
        run: docker compose -f Drink-Catalog/docker-compose.yml --env-file Drink-Catalog/.env run --rm -e NODE_ENV=test drink_api npm test


      - name: Stop services
        run: docker compose -f docker-compose.yml down

      - name: Push images to GHCR
        run: docker compose -f docker-compose.yml push
