name: CD Docker Build and Push

# on:
#   workflow_run:
#     workflows: ["CI Test"]
#     types:
#       - completed
on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    #if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # This could have been set to GITHUB_TOKEN, but I created a GHCR_PAT token instead for more granular control
      # As this is a personal repository, I used my personal account to create the token where GITHUB_TOKEN would be for an origniastion.
      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Will set up Docker Buildx following the docker-compose.yml, but will not run the containers
      - name: Build all services
        run: docker compose -f docker-compose.yml build

      # Run tests in the test containers defined in docker-compose.yml
      - name: Start dependent services
        run: docker compose -f docker-compose.yml up -d mongo

      - name: Create .env file
        run: |
          echo "PORT=5001" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "APP_ADMIN_USERNAME=${{ secrets.APP_ADMIN_USERNAME }}" >> .env
          echo "APP_ADMIN_PASSWORD=${{ secrets.APP_ADMIN_PASSWORD }}" >> .env

      - name: Run tests
        run: docker compose run --rm -e NODE_ENV=test drink_api npm test

      - name: Stop services
        run: docker compose -f docker-compose.yml down

      - name: Push images to GHCR
        run: docker compose -f docker-compose.yml push
        
  # deploy:
  #   needs: cd-build-and-push
  #   if: ${{ github.event.workflow_run.head_branch == 'main' }}
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Trigger Render Deploy
  #       run: |
  #         curl -X POST "$RENDER_DEPLOY_HOOK"
  #       env:
  #         RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
