name: CD Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # This could have been set to GITHUB_TOKEN, but I created a GHCR_PAT token instead for more granular control
      # As this is a personal repository, I used my personal account to create the token where GITHUB_TOKEN would be for an origniastion.
      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Will set up Docker Buildx following the docker-compose.yml, but will not run the containers
      - name: Build all services
        run: docker compose -f docker-compose.yml build

      # Run tests in the test containers defined in docker-compose.yml
      - name: Start dependent services
        run: docker compose -f docker-compose.yml up -d mongo

  #     - name: Run tests
  #       run: docker compose run --rm -e NODE_ENV=test drink_api npm test

  #     - name: Stop services
  #       run: docker compose -f docker-compose.yml down

  #     # TODO, consider if this should be in the deploy instead. And while the test says where it is.
  #     - name: Push images to GHCR
  #       run: docker compose -f docker-compose.yml push
        
  # deploy:
  #   name: Deploy to Render
  #   runs-on: ubuntu-latest
  #   needs: build-and-push  # Only run if build-and-push succeeded

  #   steps:
  #     - name: Trigger Render Deploy
  #       run: |
  #         curl -X POST "$RENDER_DEPLOY_HOOK"
  #       env:
  #         RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
